import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { apiGetAllProducts, apiGetBanners } from "../api/index";
export default function Home({ banners }) {
  useEffect(() => {
    console.log(banners);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>O-HI-O | 亞洲購物專家</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {banners.banners.map((banner) => (
        <div key={banner.image}>
          <Image src={banner.image} width={200} height={100} />
        </div>
      ))}
    </div>
  );
}

export async function getServerSideProps() {
  const res = await apiGetBanners();
  const banners = JSON.parse(JSON.stringify(res.data));
  return {
    props: {
      banners,
    },
  };
}
