import { useEffect } from "react";
import Head from "next/head";
import Banner from "../components/Home/Banner";
import { apiGetBanners, apiGetRecommendedProducts } from "../api/index";
import ProductCard from "../components/Global/ProductCard";
export default function Home({ banners, recommendedProducts }) {
  useEffect(() => {
    console.log(banners);
  }, []);
  return (
    <div>
      <Head>
        <title>O-HI-O | 亞洲購物專家</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner banners={banners.banners} />
      <main className="py-20px sm:py-50px max-w-1200px w-full mx-auto">
        <section className="px-15px">
          <ProductCard
            title={"推薦商品"}
            products={recommendedProducts.products}
          />
        </section>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await apiGetBanners();
  const recommendedProducts = JSON.parse(
    JSON.stringify((await apiGetRecommendedProducts()).data)
  );
  const banners = JSON.parse(JSON.stringify(res.data));
  return {
    props: {
      banners,
      recommendedProducts,
    },
  };
}
