import { useEffect} from 'react'
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {apiGetAllProducts} from '../api/index'
export default function Home() {

  useEffect(() => {
    const getProducts = async () =>{
      try{
        const { data} = await apiGetAllProducts()
        console.log()
      }catch(error){
        console.log(error)
      }
    }

    getProducts()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>O-HI-O | 亞洲購物專家</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    </div>
  );
}
